export const FETCH_RSVP_COUNT = 'FETCH_RSVP_COUNT';
export const FETCH_BUCKETS = 'FETCH_BUCKETS';
export const FETCH_RSVPS = 'FETCH_RSVPS';

export const FETCH_GROUP_INFO = 'FETCH_GROUP_INFO';
export const FETCH_RELATED_TAGS_ON_LOCATION = 'FETCH_RELATED_TAGS_ON_LOCATION';

