apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: meetup-stream
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: meetup-stream
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: meetup-stream
        image: prashilbhimani/meetupmanager:1.0.3
        resources:
          limits:
           memory: 50Mi
           cpu: "50m"
          requests:
           memory: 50Mi
           cpu: "50m"
